#INCLUDE(CMakeForceCompiler)
SET(CMAKE_SYSTEM_NAME Darwin)

set(COMPILER_PREFIX "x86_64-apple-darwin9")

find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-clang)
find_program(CMAKE_CXX_COMPILER NAMES ${COMPILER_PREFIX}-clang++)
find_program(CMAKE_AR NAMES ${COMPILER_PREFIX}-ar)
find_program(CMAKE_STRIP NAMES ${COMPILER_PREFIX}-strip)
find_program(CMAKE_RANLIB NAMES ${COMPILER_PREFIX}-ranlib)

set(CMAKE_OSX_DEPLOYMENT_TARGET 10.5)

# CHANGE THIS to your actual osxcross sdk path -DCMAKE_OSX_SYSROOT=....
set(CMAKE_OSX_SYSROOT  /opt/osxcross/target/bin/../SDK/MacOSX10.5.sdk CACHE DOC "Path to your osxcross sdk")

set(CMAKE_FIND_FRAMEWORK FIRST)
set(CMAKE_FIND_APPBUNDLE FIRST)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)